name: "Automobile"
x-type: "hlfv1"
description: "Basic network"
version: "1.0"
channels:
  automobilechannel:
    orderers:
      - orderer.excise.com

    peers:
      peer1.excise.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.fbr.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.manufacturer.com:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    chaincodes:
      - mycc:v0

organizations:
  Excise:
    mspid: ExciseMSP

    peers:
      - peer1.excise.com

    certificateAuthorities:
      - ca.excise.com

    adminPrivateKey:
      path: ../artifacts/channel/crypto-config/peerOrganizations/excise.com/users/Admin@excise.com/msp/keystore/priv_sk
    signedCert:
      path: ../artifacts/channel/crypto-config/peerOrganizations/excise.com/users/Admin@excise.com/msp/signcerts/Admin@excise.com-cert.pem

  Fbr:
    mspid: FbrMSP

    peers:
      - peer1.fbr.com

    certificateAuthorities:
      - ca.fbr.com

    adminPrivateKey:
      path: ../artifacts/channel/crypto-config/peerOrganizations/fbr.com/users/Admin@fbr.com/msp/keystore/priv_sk
    signedCert:
      path: ../artifacts/channel/crypto-config/peerOrganizations/fbr.com/users/Admin@fbr.com/msp/signcerts/Admin@fbr.com-cert.pem
  Manufacturer:
    mspid: ManufacturerMSP

    peers:
      - peer1.manufacturer.com

    certificateAuthorities:
      - ca.manufacturer.com

    adminPrivateKey:
      path: ../artifacts/channel/crypto-config/peerOrganizations/manufacturer.com/users/Admin@manufacturer.com/msp/keystore/priv_sk
    signedCert:
      path: ../artifacts/channel/crypto-config/peerOrganizations/manufacturer.com/users/Admin@manufacturer.com/msp/signcerts/Admin@manufacturer.com-cert.pem

orderers:
  orderer.excise.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.excise.com
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/ordererOrganizations/excise.com/orderers/orderer.excise.com/tls/ca.crt

  orderer2.excise.com:
    url: grpcs://localhost:8050
    grpcOptions:
      ssl-target-name-override: orderer2.excise.com
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/ordererOrganizations/excise.com/orderers/orderer2.excise.com/tls/ca.crt

  orderer3.excise.com:
    url: grpcs://localhost:9050
    grpcOptions:
      ssl-target-name-override: orderer3.excise.com
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/ordererOrganizations/excise.com/orderers/orderer3.excise.com/tls/ca.crt

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer1.excise.com:
    url: grpcs://localhost:7051

    grpcOptions:
      ssl-target-name-override: peer1.excise.com
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/peerOrganizations/excise.com/peers/peer1.excise.com/tls/ca.crt

  peer1.fbr.com:
    url: grpcs://localhost:10051

    grpcOptions:
      ssl-target-name-override: peer1.fbr.com
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/peerOrganizations/fbr.com/peers/peer1.fbr.com/tls/ca.crt

  peer1.manufacturer.com:
    url: grpcs://localhost:20051

    grpcOptions:
      ssl-target-name-override: peer1.manufacturer.com
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/peerOrganizations/manufacturer.com/peers/peer1.manufacturer.com/tls/ca.crt
#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ca.excise.com:
    url: https://localhost:7056
    httpOptions:
      verify: false
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/peerOrganizations/excise.com/ca/ca.excise.com-cert.pem

    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: ca.excise.com

  ca.fbr.com:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/peerOrganizations/fbr.com/ca/ca.fbr.com-cert.pem

    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: ca.fbr.com

  ca.manufacturer.com:
    url: https://localhost:7053
    httpOptions:
      verify: false
    tlsCACerts:
      path: ../artifacts/channel/crypto-config/peerOrganizations/manufacturer.com/ca/ca.manufacturer.com-cert.pem

    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    caName: ca.manufacturer.com
